### ISSUE TITLE
Stryker Output Directory

### ISSUE THREAD

**Issue by ohoward2001** [Trendyol/sonar-stryker-net-plugin#1]
Hi,

This is an extremely useful tool but it was difficult for me to implement at work. We have SonarQube analysis as a stage on a Jenkins Pipeline and survived/lurking mutants were not showing up initially because the default stryker output directory file path was being used which was incorrect for our project. It was only after reviewing the source code that it became clear I would need to include the output file path in the config, I think perhaps something in the docs could be added to make it clearer for people in similar situations?

Thanks
Oliver

**Comment by mstfymrtc** [comment]
Hi @ohoward2001, thanks for letting me know. You can also contribute to the docs btw
